### ISSUE TITLE
Test enter keyboard

### ISSUE THREAD

**Issue by NexiR** [etiennepinchon/aframe-material#3]
Is there any other way to test the enter input on keyboard than this ?

```
let keyboard = document.querySelector('a-keyboard')
    keyboard.addEventListener('input', (e)=>{
      console.log(e)
      if(e.detail==='\n')
        console.log('SUBMIT')
    })
```

**Comment by etiennepinchon** [comment]
Hey @NexiR !

Alright done! I added the `enter` event to the keyboard as well as physical keyboard support (great for debugging, see the updated doc for more details) ! 

Let me know if you need anything else! :)

**Comment by NexiR** [comment]
Ok man thank you ! Nice work btw, working like a charm !
