### ISSUE TITLE
Latest stable version of Edge doesn't work with aframe-material

### ISSUE THREAD

**Issue by drewpotter** [etiennepinchon/aframe-material#5]
Hi,

For some reason the latest version of Edge stable does not work with aframe-material.

I am happy to report this to Microsoft as I see no error messages in the browser.

But wanted to raise it here.

Many thanks,

Andrew
<img width="1030" alt="aframe-material" src="https://user-images.githubusercontent.com/7907456/31047379-6b907a9e-a601-11e7-8c16-a08ed16185ae.PNG">

**Comment by msitarzewski** [comment]
My experience as well.

**Comment by Utopiah** [comment]
Same here, any update, commenting out aframe-material solves it, also no warning.

**Comment by jaykm** [comment]
Still not working
